#!/bin/bash
function githome {
  dir=~/.gitls

  if [ -d "$dir" ]; then
    gh=$(<~/.gitls)
    # TODO: check if gh not empty
    if [ -z "$gh"]; then
      echo "$gh"
    else
      # TODO: check if directory exists. if not ask user to create
      echo ~/git
    fi
  else
    echo ~/git
  fi
}

gt=$(githome)

ls $gt
